# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d85f2f37f5df54dc543d6ff613c7bec47936c68e81cfeee656b759b4a874693d37154c21c358d27b622d47270bf3ae7b6e2d385a6debbb9dda66ab2d056383fe

test:
  secret_key_base: 92941182d70a991012b36fdaaaed31e6aebb56a9ae58cd9e23db711044faa1fc35c8e945af93b9fdb58e1234ae13d438a81d8f3e728526a087710e5480e99504

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
